config/routes.rb
Olive::Application.routes.draw do
  get "demo/index"
  get "demo/ux_wheel"
  get "demo/boxes"
  get "demo/olive"
  root :to=>'demo#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end
  def ux_wheel
  end
  def olive
  end
  def boxes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/demo/boxes.erb
<!--<script type="text/javascript" src="http://www.linkedin.com/js/public-profile/widget-os.js"></script>-->

<style type="text/css">
</style>

<div class="boxes">
  <div id="title" class="double-wide">
    <h1>NDPSoftware</h1>
    <h4>Selected Projects &mdash; Software Development by Andrew Peterson</h4>
  </div>
  <div class="house">
    <h3>About Us</h3>
    <h4>Resume / C.V.</h4>
    <p>Start-ups, consulting, non-profits...</p>
    <a class="linkedin-profileinsider-popup" href="http://www.linkedin.com/in/ndpsoftware">View LinkedIn Profile</a>
  </div>
  <div class="visualization" id="ux_spoke" data-height="2" data-width="2">
    <h3>Ux Spoke</h3>
    <h4>Visualization</h4>

    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
    <p>Common Software Usability Questions: As you develop or refine a software product, it's easy to get stuck in a
      rut, running tests that aren't that helpful or focusing on Google Analytics. That tool that worked so well may no
      longer be the right tool for the questions you have now. The UX/Spoke tool is designed to help you explore many of
      the different tools in common practice.</p>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
    <a href="http://uxspoke.com">View visualization</a>
  </div>
  <div class="house">
    <h3>Blog</h3>
    <h4></h4>
    <p>Some of my recent thoughts are expressed here</p>
    <a href="http://ndpsoft.blogspot.com">Read Blog</a>
  </div>
  <div class="dev_tool" id="csster" data-height="2" data-width="2">
    <h3>Csster</h3>
    <h4>CSS within Javascript</h4>
    <h4>Development Tool</h4>

    <p>Concisely generates CSS style rules within Javascript. Features:
      <ul>
      <li>standard "object literal"/JSON format with good editor support;
      <li>nesting to DRY up stylesheets;
      <li>color functions like darken and saturate;
      <li>built-in macros for common CSS idioms like clearfix, rounded corners, drop shadows;
      <li>and extension points.
          </ul>
    </p>
    <a href="http://github.com/ndp/csster">Github project page</a>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
  </div>
  <div class="jquery_plugin dev_tool">
    <h3>Wizardize</h3>
    <h4>JQuery plugin</h4>

    <p>A plugin to separate a regular HTML form into wizard steps.</p>
    <a href="http://github.com/ndp/wizardize">Project Home Page</a>

    <div class="tags">api_design javascript usability testing collaboration</div>
  </div>
  <div class="collaboration" id="bedsider" data-width="2">
    <h3>Bedsider</h3>
    <h4>Software Engineering Collaboration</h4>
    <p>I led development in collaboration with IDEO on the nation's first "birth control support network".</p>
    <a href="http://bedsider.org/methods">View Site</a>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
  </div>
  <div class="visualization">
    <h3>BootyLog</h3>
    <h4>Visualizations</h4>

    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
  </div>
  <div class="cheatsheet" id="hibernate_mapping_cheatsheet">
    <h3>Hibernate Mapping</h3>
    <h4>Cheatsheet</h4>
    <a href="http://www.ndpsoftware.com/HibernateMappingCheatSheet.html">View Details</a>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
  </div>
  <div class="visualization" data-height="2" data-width="2">
    <h3>Git Cheatsheet</h3>
    <h4>Interactive Visualization</h4>

    <p>As I dove into learning Git, I was initially confused about where my code was.
      I felt pretty confident that git hadn't lost anything, but less confident I could get it back readily.
      It's distributed, so I expect my code will be more places, but it's much more complex than Subversion or CVS.
      Once I figured out the basic locations that things could be, the second challenge was to understand the
      commands that can affect them. This is my visualization as I figured this out. </p>
    <a href="http://www.ndpsoftware.com/git-cheatsheet.html">View Git Cheatsheet</a>
    <div class="tags">prototype visual_design ui_design product_design mini_project javascript usability
      education visualization
    </div>
  </div>
  <div id="so" class="house">
    <h3>S.O.</h3>
    <h4>Stack Overflow Q &amp; A</h4>
    <!--<p><img src="http://stackoverflow.com/users/flair/114584.png?theme=clean" width="208" height="58"-->
         <!--alt="Stack Overflow profile for ndp at Stack Overflow, Q&amp;A for professional and enthusiast programmers"-->
         <!--title="Stack Overflow profile for ndp at Stack Overflow, Q&amp;A for professional and enthusiast programmers"></p>-->
    <a href="http://stackoverflow.com/users/114584/ndp">View S.O. Profile</a>
  </div>
  <div class="house">
    <h3>Clients</h3>
    <h4>&nbsp;</h4>
    <p>Companies, clients and people we've worked with.</p>
    <a href="http://www.ndpsoftware.com/clients.php">View Clients</a>
  </div>
  <div class="visualization" id="agile_methods" data-width="2">
    <h3>Agile Processes</h3>
    <h4>Visualization</h4>

    <p>A quick visualization to understand the differences between "agile", XP, scrum, etc.</p>
    <a href="http://ndpsoft.blogspot.com/2009/09/scrum-xp-agile-and-visualizing.html">View Blog post</a>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
  </div>
  <div class="dev_tool" data-width="2">
    <h3>Ayudante</h3>
    <h4>Ruby Gem</h4>

    <p>TestUnit test helpers for pre- and post-conditions and a few other items missing from RoR.</p>
    <a href="http://ndpsoft.blogspot.com/2010/01/assert-changes-and-fixture-test-helpers.html">View Blog post</a>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
  </div>
  <div class="visualization">
    <h3>Scriptaculous Effects Demo</h3>
    <h4>Visualization</h4>

    <!--<p>A quick demonstration of Scriptaculous animation effects.</p>-->
    <a href="http://ndpsoftware.com/ScriptaculousEffectsDemo.php">View demo</a>
    <div class="tags">prototype visual_design ui_design mini_project javascript visualization
    </div>
  </div>
  <div class="dev_tool">
    <h3>CSS Best Practices</h3>
    <h4>Technical Writing</h4>
    <a href="http://www.ndpsoftware.com/CssBestPractices.php">View document</a>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
  </div>
  <div class="jquery_plugin dev_tool" id="show_char_limit" data-width="2">
    <h3>Show Char Limit</h3>
    <h4>JQuery plugin</h4>
    <p>Echos characters available within input/textarea fields.</p>
    <a href="http://www.ndpsoftware.com/show_char_limit.php">View Plugin home page</a>

    <div class="tags">api_design mini_project javascript testing</div>
  </div>

  <div class="cheatsheet" id="jspx_cheatsheet">
    <h3>JSP XML</h3>
    <h4>Cheatsheet</h4>
    <a href="http://www.ndpsoftware.com/JSPXMLCheatSheet.html">View cheatsheet</a>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
  </div>



  <div class="jquery_plugin dev_tool">
    <h3>Color Spy</h3>
    <h4>JQuery plugin</h4>

    <p>A simple eye-dropper plugin to determine colors from elements.</p>
    <a href="http://github.com/ndp/color_spy">View Github project page</a>

    <div class="tags">api_design javascript</div>
  </div>
  <div class="visualization" id="tracker_story_maps">
    <h3>Story Mapper</h3>
    <h4>Visualization</h4>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
      education visualization
    </div>
  </div>
  <div class="prototype" id="chklistr">
    <h3>chklistr</h3>
    <h4>Site Prototype</h4>
    <p>Find, use and share all sorts of checklists.</p>
    <a href="http://chklistr.com/">View prototype</a>
    <div class="tags">prototype visual_design ui_design product_design javascript</div>
  </div>
  <div class="prototype">
    <h3>who-eats-what</h3>
    <h4>Site Prototype</h4>
    <a href="http://who-eats-what.heroku.com/">View prototype</a>
    <div class="tags">prototype ui_design product_design mini_project
      education visualization
    </div>
  </div>
  <div class="prototype" id="difftionary">
    <h3>difftionary</h3>
    <h4>Site prototype</h4>

    <p>An online dictionary drawing out distinctions between words.</p>
    <a href="http://difftionary.com/">View prototype</a>
    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability
    </div>
  </div>
  <div class="visualization" data-height="2">
    <h3>Programming Languages I've Used</h3>
    <h4>Visualization</h4>
    <p>Quick bar chart of the programming languages Andy has used throughout his career. Created to demonstrate concise CSS and Javascript
      style.</p>
    <a href="http://ndpsoft.blogspot.com/2010/09/most-resumes-are-pretty-boring.html#more">View Languages</a>

    <div class="tags">prototype visual_design ui_design product_design mini_project canvas javascript usability testing
      ruby java collaboration education visualization
    </div>
  </div>
</div>

app/views/demo/circle.html.erb
<style type="text/css">
  #answers {
    padding: 20px;
    border: 1px dotted #eee;
    background-color: #eee;
    position: absolute;
    top: 100px;
    left: 800px;
    width: 300px;
  }
</style>

<canvas id="circle" width='700' height='700' ></canvas>
<div id="answers"></div>

app/views/demo/index.html.erb
<h1>Demo#index</h1>


<%= link_to 'UX Wheel', demo_ux_wheel_path %>
<%= link_to 'Olive', demo_olive_path %>

app/views/demo/olive.html.erb
<h1>Demo#olive</h1>


<canvas id="graph" width='300' height='235' ></canvas>


<a id="animate" href="#">Animate!</a>

app/views/demo/ux_wheel.html.erb
<canvas id="circle" width='800' height='800' ></canvas>
<div id="answers">
</div>

<div id="about">
  <h4>What's going on here?<span>click to hide</span></h4>
  <h1>Common Software Usability Questions<span> (and how to get answers!)</span></h1>
  <p>Test your understanding of your users, the problems they face, and your solution. The earlier you test your assumptions,
  the less time (and money) you'll spend designing and building the wrong product.</p>
  <p>On this wheel are some common questions that users can help answer.
  Click on any question to see how to get answers.</p>
  <h5>Colors</h5>
  <p>The lighter the color, the earlier it can be answered. In this model there are three phases:</p>
  <ol>
    <li class="requirements">before</li>
    <li class="design">design & build</li>
    <li class="test">refine</li>
  </ol>
  <p><em>Before</em> is all the activities done before you are ready to build the product-- mostly understanding the user and problems.
    <em>Refine</em> are activities around improving a working product.</p>
  <h5>Feedback</h5>
  <p>If you disagree or have new ideas, drop me a line at <a href="mailto:ndp+wheel@mac.com">ndp+wheel@mac.com</a></p>
  <h5>And...</h5>
  <p>You can use the arrow keys (up/down) to cycle through the wheel, as well as the space bar just to let it spin (and stop).</p>
  <p class="copyright">Copyright &copy; 2010 <a href="http://ndpsoftware.com">Andrew J. Peterson, NDP Software.</a> All Rights Reserved.</p>
</div>

app/views/demo/wheel.html.erb
<h1>Common Software Usability Questions<span> (and how to get answers!)</span></h1>
<div class="copyright">Copyright &copy; 2010 <a href="http://ndpsoftware.com">Andrew J. Peterson.</a> All Rights Reserved.</div>
<canvas id="circle" width='800' height='800' ></canvas>
<div id="answers">
  <h5>Don't spin the wheel...</h5>
  <p>Early on test your understanding of your users and the problems they face. The earlier you test your assumptions,
  the less time (and money) you'll spent designing and building the wrong product.</p>
  <p>On this wheel are some common questions that users can help answer. </p>
  <p>Click on any question to see how to get answers.</p>
  <p>You can use the arrow keys (up/down) to cycle through the wheel, as well as the space bar just to let it spin (and stop).</p>
  <h5>Colors</h5>
  <p>The darker the color, the earlier it can be answered:</p>
  <ol>
    <li style="background-color: #4D4D80; color: white">requirements</li>
    <li style="background-color: #7070A9; color: white">design</li>
    <li style="background-color: #8080B3; color: white">build &amp; test</li>
  </ol>
  <p>If you disagree or have new ideas, drop me a line at <a href="mailto:ndp+wheel@mac.com">ndp+wheel@mac.com</a></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Olive</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.2.min.js',
                             'jquery-ui-1.8.5.custom.min.js',
                             'jquery.mousewheel.js',
                             'csster',
                             'once',
                             'color_factory',
                             'usability_questions',
                             'wheel', 'olive', 'application', 'ux_wheel' %>
  <%= csrf_meta_tag %>
  <style>
      body {
          background-color: white;
      }
  </style>
</head>
<body>

<%= yield %>

</body>
</html>